
export const MESSAGE_BUS_CONFIG = {
    LOG: true,
    INFO: true,
    DEBUG: true,
    WARN: true,
    ERROR: true,
    MSEVENTS: false,
    IMAGESEARRCH: false,
    DEEPSEARCH: false,
    EXTRASEARCH: false,
    LOGEXTRASEARCH: false,
    IMGSEARCH: false,
    METADATA: true,
    HIGHLIGHTER: false,
    LOGPARSEIMG: false,
    LOGEXIFDESCPARSE: false,
    MESSAGEPASSING: false,
    EXIFREADYLOGS: false,
    EXIFLOADPARSELOGS: false,
    CREATEPOPUPLOGS: false,
    FETCHERLOGGING: true,
    CONTENTMESSAGEHANDLERLOGGER: false,
}